// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.ArduinoCommunicationsTest3566;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DigitalInput arduinoSerialSwitchInterfaceLimitSwitch1;
    public static DigitalInput arduinoSerialSwitchInterfaceLimitSwitch2;
    public static DigitalInput arduinoSerialSwitchInterfaceLimitSwitch3;
    public static DigitalInput arduinoSerialSwitchInterfaceLimitSwitch4;
    public static AnalogInput arduinoSerialSwitchInterfaceValueFromArduino_Analog;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        arduinoSerialSwitchInterfaceLimitSwitch1 = new DigitalInput(0);
        LiveWindow.addSensor("ArduinoSerialSwitchInterface", "Limit Switch 1", arduinoSerialSwitchInterfaceLimitSwitch1);
        
        arduinoSerialSwitchInterfaceLimitSwitch2 = new DigitalInput(1);
        LiveWindow.addSensor("ArduinoSerialSwitchInterface", "Limit Switch 2", arduinoSerialSwitchInterfaceLimitSwitch2);
        
        arduinoSerialSwitchInterfaceLimitSwitch3 = new DigitalInput(2);
        LiveWindow.addSensor("ArduinoSerialSwitchInterface", "Limit Switch 3", arduinoSerialSwitchInterfaceLimitSwitch3);
        
        arduinoSerialSwitchInterfaceLimitSwitch4 = new DigitalInput(3);
        LiveWindow.addSensor("ArduinoSerialSwitchInterface", "Limit Switch 4", arduinoSerialSwitchInterfaceLimitSwitch4);
        
        arduinoSerialSwitchInterfaceValueFromArduino_Analog = new AnalogInput(0);
        LiveWindow.addSensor("ArduinoSerialSwitchInterface", "ValueFromArduino_Analog", arduinoSerialSwitchInterfaceValueFromArduino_Analog);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
