// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.Official_Competition_Code_2015;

import org.usfirst.frc3566.Official_Competition_Code_2015.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);
    
    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.
    
    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:
    
    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());
    
    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());
    
    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());

    public Joystick xBoxController;
    public JoystickButton Button8;
    public JoystickButton Button5;
    public JoystickButton Button6;
    public JoystickButton Button4;
    public JoystickButton Button3;
    public JoystickButton Button2;
    public JoystickButton Button1;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
    	xBoxController = new Joystick(0);
    	
    	Button8 = new JoystickButton(xBoxController,8);
    	Button8.whenPressed(new ResetElevator());
    	Button5 = new JoystickButton(xBoxController,5);
    	Button5.whenPressed(new RaiseElevator());
    	Button5.whenReleased(new StopElevator());
    	Button6 = new JoystickButton(xBoxController,6);
    	Button6.whenPressed(new LowerElevator());
    	Button6.whenReleased(new StopElevator());
    	Button4 = new JoystickButton(xBoxController,4);
    	Button4.whenPressed(new Dump());
    	Button3 = new JoystickButton(xBoxController,3);
    	Button3.whenPressed(new RaiseHookDistance());
    	Button2 = new JoystickButton(xBoxController,2);
    	Button2.whileHeld(new RaisePicker());
    	Button1 = new JoystickButton(xBoxController,1);
    	Button1.whileHeld(new LowerPicker());
    	
    	
    	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


	    
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous", new Autonomous());

        SmartDashboard.putData("RaiseElevator", new RaiseElevator());

        SmartDashboard.putData("LowerElevator", new LowerElevator());

        SmartDashboard.putData("StopElevator", new StopElevator());

        SmartDashboard.putData("Reset Elevator", new ResetElevator());

        SmartDashboard.putData("RaisePicker", new RaisePicker());

        SmartDashboard.putData("LowerPicker", new LowerPicker());

        SmartDashboard.putData("StopPicker", new StopPicker());

        SmartDashboard.putData("LiftAndHoldPicker", new LiftAndHoldPicker());

        SmartDashboard.putData("Dump", new Dump());

        SmartDashboard.putData("DriveStraight", new DriveStraight());

        SmartDashboard.putData("Creep", new Creep());
        
        SmartDashboard.putData("turn", new TurnAngle(90));


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        
        
    }
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

