// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.FrogTongueV2Friday.subsystems;

import org.usfirst.frc3566.FrogTongueV2Friday.RobotMap;
import org.usfirst.frc3566.FrogTongueV2Friday.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class FrogTongue extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController speedController0 = RobotMap.frogTongueSpeedController0;
    SpeedController speedController1 = RobotMap.frogTongueSpeedController1;
    RobotDrive frogTongueDrive01 = RobotMap.frogTongueFrogTongueDrive01;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    
    public void stopFrogMotors(){
    	frogTongueDrive01.tankDrive(0, 0);
    }
    
    public void startFrogMotors(){
    	frogTongueDrive01.tankDrive(RobotMap.FROG_MOTOR_SPEED_VALUE, RobotMap.FROG_MOTOR_SPEED_VALUE);
    		
    
    }
    
public void reverseFrogMotors(){
	frogTongueDrive01.tankDrive(RobotMap.FROG_MOTOR_SPEED_VALUE_REVERSE, RobotMap.FROG_MOTOR_SPEED_VALUE_REVERSE);
    }
}

