// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.Official_Competition_Code_2015.subsystems;

import org.usfirst.frc3566.Official_Competition_Code_2015.RobotMap;
import org.usfirst.frc3566.Official_Competition_Code_2015.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class ConveyorSwitch extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalInput e1 = RobotMap.conveyorSwitchE1;
    DigitalInput e2 = RobotMap.conveyorSwitchE2;
    DigitalInput e3 = RobotMap.conveyorSwitchE3;
    DigitalInput e4 = RobotMap.conveyorSwitchE4;
    DigitalInput e5 = RobotMap.conveyorSwitchE5;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public boolean getE5(){
    	return (false)==(e5.get());
    }
    public boolean getE1(){
    	return (false)==(e5.get());
    }
    public boolean getE2(){
    	return (false)==(e2.get());
    }
    public boolean getE3(){
    	return (false)==(e3.get());
    }
    public boolean getE4(){
    	return (false)==(e4.get());
    }
}

