// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.Official_Competition_Code_2015.subsystems;

import org.usfirst.frc3566.Official_Competition_Code_2015.Robot;
import org.usfirst.frc3566.Official_Competition_Code_2015.RobotMap;
import org.usfirst.frc3566.Official_Competition_Code_2015.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Mecanum extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Mecanum_Drive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void Drive(double sr, double st){
    	double x;
    	if (Math.abs(Robot.oi.xBoxController.getRawAxis(0))>0.15){
    		x = (-1)*sr*Robot.oi.xBoxController.getRawAxis(0);
    	} else {
    		x = 0;
    	}
    	double y;
    	if (Math.abs(Robot.oi.xBoxController.getRawAxis(1))>0.15){
    		y = sr*Robot.oi.xBoxController.getRawAxis(1);
    	} else {
    		y = 0;
    	}
    	double rot;
    	if (Math.abs(Robot.oi.xBoxController.getRawAxis(4))>0.15){
    		rot = (-1)*st*Robot.oi.xBoxController.getRawAxis(4);
    	} else {
    		rot = 0;
    	}
    	RobotMap.mecanumMecanum_Control.mecanumDrive_Cartesian(x, y, rot, 0);
    }
}

