// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.Official_Competition_Code_2015.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Autonomous extends CommandGroup {
    
	public Autonomous() {
		//addSequential(new RaiseHookDistance(2));
		//addSequential(new DriveStraight(5));
		addSequential(new RaiseHookDistance(2.3));
		addSequential(new DriveStraight(4.7));
		/*addSequential(new BackUp());
		addSequential(new DriveLeft());
		addSequential(new LowerHookDistance(0.2)); // Kevin: shouldn't we lower further than this? -- Mr. B
		addSequential(new Creep());
		addSequential(new RaiseHookDistance(2.8));
		addSequential(new BackUp());
		addSequential(new DriveLeft());
		addSequential(new LowerHookDistance(0.2));
		addSequential(new Creep());
		addSequential(new RaiseHookDistance(0.5));
		addSequential(new DriveBack());
		addSequential(new Dump());*/
	}
}
