// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.Official_Competition_Code_2015.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Autonomous extends CommandGroup {
    
	public Autonomous() {
		this(1, 0);
	}
	
	public Autonomous(int totes, int barrels) {
    	/* ready position */
    	//addParallel(new LowerPicker());
		addSequential(new Dump());
    	
    	if (totes > 0) {
        	/* approach and lift first tote */
    		toteLift();
        	
        	if (barrels == 1) {
            	/* lift barrel */
            	//addSequential(new LiftAndHoldPicker());
        	} else if (barrels > 1) {
        		//addSequential(new RaisePicker());
        		addParallel(new LowerPicker());
        	}
        	
        	if (totes > 1) {
        		toteLift();
        	}
        	
        	if (barrels > 1) {
        		addSequential(new LiftAndHoldPicker());
        	}
        	
        	if (totes > 2) {
        		toteLift();
        	}
    	}
    	
    	/* run to the auto zone */
    	addSequential(new TurnAngle(90));
    	addSequential(new DriveStraight(5));
    	
    	/* stack totes */
    	addSequential(new Dump());
    }
	
	private void toteLift() {
    	addSequential(new DriveStraight());
    	addParallel(new Creep());
    	addSequential(new RaiseHookDistance());
	}
}
