// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3566.Official_Competition_Code_2015.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3566.Official_Competition_Code_2015.Robot;

/**
 *
 */
public class  DisplayValues extends Command {

    public DisplayValues() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        //requires(Robot.elevator);
    	requires(Robot.bottomSwitches);
    	requires(Robot.conveyorSwitch);
    	requires(Robot.elevator);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        SmartDashboard.putBoolean("B1", Robot.bottomSwitches.getB1());
        
        SmartDashboard.putBoolean("B2", Robot.bottomSwitches.getB2());
        
        SmartDashboard.putBoolean("B3", Robot.bottomSwitches.getB3());
        
        SmartDashboard.putBoolean("B4", Robot.bottomSwitches.getB4());
        
        SmartDashboard.putBoolean("E1", Robot.conveyorSwitch.getE1());
        
        SmartDashboard.putBoolean("E2", Robot.conveyorSwitch.getE2());
        
        SmartDashboard.putBoolean("E3", Robot.conveyorSwitch.getE3());
        
        SmartDashboard.putBoolean("E4", Robot.conveyorSwitch.getE4());
        
        SmartDashboard.putBoolean("E5", Robot.conveyorSwitch.getE5());
        
        SmartDashboard.putDouble("ElevatorPosition", Robot.elevator.getPositionPotentiometer());
        
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
