// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3566.OfficialCode.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc3566.OfficialCode.RobotConstants;

/**
 *
 */
public class FireCatapultAtDistance extends CommandGroup {

    /**
     * Assumes the bot is already in motion... set a distance at which to fire
     * the catapult along the current path. By default the distance at which the
     * catapult will fire is "as soon as the bot's at full speed".
     */
    public FireCatapultAtDistance() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.
        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        this(RobotConstants.DRIVETRAIN_DISTANCE_TO_FULL_SPEED);
    }

    /**
     * Assumes the bot is already in motion... set a distance at which to fire
     * the catapult along the current path.
     *
     * @param distanceInFeet The distance at which to fire the catapult
     */
    public FireCatapultAtDistance(double distanceInFeet) {
        addSequential(new PauseForDistance(distanceInFeet));
        addSequential(new FireCatapult());
    }
}
