// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3566.OfficialCode.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3566.OfficialCode.Robot;
    // Make this return true when this Command no longer needs to run execute()
/**
 * Joystick control of El Toro elevator
 */
public class JoystickElToro extends Command {
    public JoystickElToro() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elToro);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        //Uses RT and LT to Raise/lower El Toro 
        //Only on xBox
        /*
         if (Math.abs(Robot.oi.xBoxDriver.getRawAxis(3))>0.2){      
         Robot.elToro.lower(Robot.oi.xBoxDriver.getRawAxis(3));
         } 
         */
    }
    protected boolean isFinished() {
        return false;
    }
    protected void end() {
        Robot.elToro.stop();
    }
    protected void interrupted() {
        end();
    }
}
