// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3566.OfficialCode.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3566.OfficialCode.Robot;
import org.usfirst.frc3566.OfficialCode.RobotConstants;
/**
 *
 */
public class  RaiseElToro extends Command {
    
    private double speed = RobotConstants.EL_TORO_RAISE_SPEED;
    private double time = -1;
    
    public RaiseElToro() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elToro);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    public RaiseElToro(double percentageOfFullSpeed) {
        speed = percentageOfFullSpeed;
        requires(Robot.elToro);
    }
    
    public RaiseElToro(double percentageOfFullSpeed, double timeInSeconds) {
        speed = percentageOfFullSpeed;
        time = timeInSeconds;
        requires(Robot.elToro);
    }
    
    // Called just before this Command runs the first time
    protected void initialize() {
        if (time > 0) {
            setTimeout(time);
        }
        Robot.elToro.raise(speed);
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Robot.elToro.atUpperLimit() || (time > 0 && isTimedOut());
    }
    // Called once after isFinished returns true
    protected void end() {
       // Robot.elToro.lower();
        Robot.elToro.stop();
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
